server:
    port: 8082


spring:
  application:
    name: grade-submission

  datasource:
    name: grade-submission
    username: sa
    password: 
    url: jdbc:h2:mem:grade-submission

  h2:
    console:
      enabled: true
      path: /h2